"""
Classes for handling comparison files generated by the Fortran version of sfit.
"""

import numpy as np


class FortranSFitFile51(object):
    """
    Class to parse the comparison file generated by
    the Fortran version of sfit.
    """
    def __init__(self, filename):
        with open(filename, 'r') as input_file:
            key = None
            for line in input_file.readlines():
                words = line.split()
                if words[0] == '#':
                    key = words[-1]
                    continue
                elif len(words) == 1:
                    value = float(words[0])
                else:
                    value = np.array([float(item) for item in words])

                self.__setattr__(key, value)

